# Generated by Django 4.0.4 on 2022-06-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='calorias',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
