# Generated by Django 4.0.4 on 2022-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_alter_alimento_calorias_alter_alimento_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='alimento',
            field=models.ManyToManyField(to='seeker.alimento'),
        ),
    ]
