# Generated by Django 4.0.4 on 2022-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_receta_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='grasas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteina',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcion', models.CharField(max_length=200, null=True)),
                ('alimento', models.ManyToManyField(to='seeker.alimento')),
                ('receta', models.ManyToManyField(to='seeker.receta')),
            ],
        ),
    ]
