# Generated by Django 4.0.3 on 2022-06-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_alimento_fecha_creacion_receta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='calorias',
        ),
    ]
