# Generated by Django 4.0.5 on 2022-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0006_remove_receta_calorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=500, null=True)),
                ('instrucciones_salida', models.TextField(blank=True)),
            ],
        ),
    ]
