# Generated by Django 4.0.5 on 2022-11-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0007_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio_Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(max_length=200, null=True)),
                ('piso', models.CharField(max_length=200, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.lugar')),
            ],
        ),
    ]
