# Generated by Django 4.0.5 on 2022-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0008_edificio_piso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='instrucciones_salida',
        ),
        migrations.AddField(
            model_name='edificio_piso',
            name='instrucciones_salida',
            field=models.TextField(blank=True),
        ),
    ]
